[tool.poetry]
name = "resume"
version = "0.1.0"
description = ""
authors = ["hong <j50508@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pypdf = "^3.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
